# The Field Guide Update - data module
# KITCHEN: tool catalog | EQUIPMENT: per-recipe tools | FACTS: per-recipe data sheet
# CLUSTERS / USES / SIMILAR_PAIRS: the family tree

KITCHEN = {
    "chefs-knife": {"name": "Chef's knife", "cat": "blades", "url": "https://en.wikipedia.org/wiki/Chef%27s_knife",
        "blurb": "The one tool that touches everything. Pinch grip, weight forward, and it quietly does ninety percent of the kitchen's work."},
    "cutting-board": {"name": "Cutting board", "cat": "blades", "url": "https://en.wikipedia.org/wiki/Cutting_board",
        "blurb": "Wood or plastic, never glass - glass dulls edges and hates your knife back. Own two: one for alliums, one for fruit."},
    "mandoline": {"name": "Mandoline", "cat": "blades", "url": "https://en.wikipedia.org/wiki/Mandoline",
        "blurb": "Paper-thin slices at machine speed, and zero mercy for fingertips. Use the guard. Always use the guard."},
    "box-grater": {"name": "Box grater", "cat": "blades", "url": "https://en.wikipedia.org/wiki/Grater",
        "blurb": "Four sides, four opinions. The coarse face is for cheese mountains; the small one is for nutmeg grudges."},
    "microplane": {"name": "Microplane / zester", "cat": "blades", "url": "https://en.wikipedia.org/wiki/Microplane",
        "blurb": "Turns hard cheese to snow and citrus zest to perfume. A carpenter's rasp that defected to the kitchen, luckily."},
    "pepper-mill": {"name": "Pepper mill", "cat": "blades", "url": "https://en.wikipedia.org/wiki/Black_pepper",
        "blurb": "Ground pepper goes stale in minutes. The mill is the difference between seasoning and decoration."},
    "cast-iron-skillet": {"name": "Cast-iron skillet", "cat": "pots", "url": "https://en.wikipedia.org/wiki/Cast-iron_cookware",
        "blurb": "Slow to heat, impossible to scare. It holds temperature when cold meat hits the pan, which is where crusts come from."},
    "frying-pan": {"name": "Frying pan / saute pan", "cat": "pots", "url": "https://en.wikipedia.org/wiki/Frying_pan",
        "blurb": "The everyday workhorse - wide, flat sides, and honest about how much oil you actually poured."},
    "dutch-oven": {"name": "Dutch oven", "cat": "pots", "url": "https://en.wikipedia.org/wiki/Dutch_oven",
        "blurb": "The heavy lidded pot that braises, fries, bakes bread and outlives its owner. Buy once, will it to someone."},
    "stockpot": {"name": "Stockpot", "cat": "pots", "url": "https://en.wikipedia.org/wiki/Stockpot",
        "blurb": "Tall and patient - built for broths, blanching, and boiling pasta water like you mean it. Salt it like the sea."},
    "saucepan": {"name": "Saucepan", "cat": "pots", "url": "https://en.wikipedia.org/wiki/Saucepan",
        "blurb": "Where sauces, rice and custards happen. The tall sides slow evaporation on purpose - that is the feature."},
    "wok": {"name": "Wok", "cat": "pots", "url": "https://en.wikipedia.org/wiki/Wok",
        "blurb": "Curved, thin, screaming hot. A round bottom loves fire; a flat bottom forgives electric stoves. Either way: mise en place or perish."},
    "paella-pan": {"name": "Paella pan", "cat": "pots", "url": "https://en.wikipedia.org/wiki/Paella_pan",
        "blurb": "Wide, shallow, dented steel. Maximum rice touching the bottom is the entire design brief - that is where the socarrat lives."},
    "baking-dish": {"name": "Baking dish", "cat": "pots", "url": "https://en.wikipedia.org/wiki/Cookware_and_bakeware",
        "blurb": "Ceramic or glass, goes oven-to-table, and hosts every gratin, mac and shepherd's pie you will ever love."},
    "ramekin": {"name": "Ramekins", "cat": "pots", "url": "https://en.wikipedia.org/wiki/Ramekin",
        "blurb": "Small ceramic cups with big jobs: creme brulee, lava cake, and mise en place for adults."},
    "oven": {"name": "Oven", "cat": "fire", "url": "https://en.wikipedia.org/wiki/Oven",
        "blurb": "The room where nothing is stirred. Every oven has hot spots; learn yours - they are characters."},
    "stove": {"name": "Stovetop", "cat": "fire", "url": "https://en.wikipedia.org/wiki/Stove",
        "blurb": "Gas forgives, induction responds, electric insists. Learn which one you married."},
    "grill": {"name": "Grill / grill pan", "cat": "fire", "url": "https://en.wikipedia.org/wiki/Grilling",
        "blurb": "Char is a flavor, not a mistake. A grill pan gives you the stripes and part of the smoke, indoors, year-round."},
    "skewers": {"name": "Skewers", "cat": "fire", "url": "https://en.wikipedia.org/wiki/Skewer",
        "blurb": "Soak the wooden ones for thirty minutes or watch them burn - a small ritual that protects big flavor."},
    "blowtorch": {"name": "Kitchen torch", "cat": "fire", "url": "https://en.wikipedia.org/wiki/Blowtorch",
        "blurb": "The only tool that announces dessert is not done until something is caramelized. Keep it moving, 5 cm from the sugar."},
    "thermometer": {"name": "Instant-read thermometer", "cat": "prep", "url": "https://en.wikipedia.org/wiki/Meat_thermometer",
        "blurb": "Ends the guessing career of overcooked chicken, shy custards and lukewarm oil. The cheapest upgrade in the kitchen."},
    "kitchen-scale": {"name": "Kitchen scale", "cat": "prep", "url": "https://en.wikipedia.org/wiki/Weighing_scale",
        "blurb": "Grams do not argue. Baking's entire personality is a scale; everything else is vibes and apology."},
    "measuring-cups": {"name": "Measuring cups & spoons", "cat": "prep", "url": "https://en.wikipedia.org/wiki/Measuring_cup",
        "blurb": "For cooks who level the spoon with a finger. No judgment. Some judgment."},
    "mixing-bowl": {"name": "Mixing bowls", "cat": "prep", "url": "https://en.wikipedia.org/wiki/Mixing_bowl",
        "blurb": "The kitchen's true supporting cast. You need more than you own, and the day you learn this is the day you buy four."},
    "whisk": {"name": "Whisk", "cat": "prep", "url": "https://en.wikipedia.org/wiki/Whisk",
        "blurb": "Eight wires of persuasion - for emulsions, custards, and rescuing lumpy plans at the last second."},
    "wooden-spoon": {"name": "Wooden spoon", "cat": "prep", "url": "https://en.wikipedia.org/wiki/Wooden_spoon",
        "blurb": "Does not scratch, melt, or conduct heat into your hand - and stirs risotto like it is the job. It is."},
    "spatula": {"name": "Spatula", "cat": "prep", "url": "https://en.wikipedia.org/wiki/Spatula",
        "blurb": "Flexible for fish, firm for flipping. The boundary between cooking and juggling."},
    "tongs": {"name": "Tongs", "cat": "prep", "url": "https://en.wikipedia.org/wiki/Tongs",
        "blurb": "The extension of your hand that does not burn. Flip, toss, lift, serve - then click them twice, for confidence."},
    "ladle": {"name": "Ladle", "cat": "prep", "url": "https://en.wikipedia.org/wiki/Ladle_(spoon)",
        "blurb": "For serving soup and for feeding hot stock into risotto one slow circle at a time."},
    "colander": {"name": "Colander", "cat": "prep", "url": "https://en.wikipedia.org/wiki/Colander",
        "blurb": "The pasta's exit strategy. Also rinses chickpeas, drains noodles, and holds fruit at a picnic."},
    "fine-sieve": {"name": "Fine-mesh sieve", "cat": "prep", "url": "https://en.wikipedia.org/wiki/Sieve",
        "blurb": "The difference between sauce and silk - and the bodyguard of every custard ever made."},
    "spider": {"name": "Spider / skimmer", "cat": "prep", "url": "https://en.wikipedia.org/wiki/Skimmer_(utensil)",
        "blurb": "A basket on a stick for lifting things out of hot oil or blanching water without bringing the bath with them."},
    "citrus-juicer": {"name": "Citrus squeezer", "cat": "prep", "url": "https://en.wikipedia.org/wiki/Juicer",
        "blurb": "Half a lemon's juice hides. This finds all of it, seeds staying behind where they belong."},
    "mortar-pestle": {"name": "Mortar & pestle", "cat": "prep", "url": "https://en.wikipedia.org/wiki/Mortar_and_pestle",
        "blurb": "Crushing releases oils that grinding cannot reach. The oldest machine in the kitchen, still undefeated."},
    "bench-scraper": {"name": "Bench scraper", "cat": "prep", "url": "https://en.wikipedia.org/wiki/Bench_scraper",
        "blurb": "Dough handler, board cleaner, and the smash burger's secret weapon. Three tools in a flat metal lie."},
    "pastry-brush": {"name": "Pastry brush", "cat": "prep", "url": "https://en.wikipedia.org/wiki/Pastry_brush",
        "blurb": "Egg wash, melted butter, glaze - the difference between pale and golden is one swipe."},
    "kitchen-twine": {"name": "Kitchen twine", "cat": "prep", "url": "https://en.wikipedia.org/wiki/Twine",
        "blurb": "Ties roasts, trusses poultry and holds the bouquet garni together while it lectures the pot."},
    "potato-masher": {"name": "Potato masher", "cat": "prep", "url": "https://en.wikipedia.org/wiki/Potato_masher",
        "blurb": "For roofs with texture. Machines make glue; arms make mash."},
    "meat-mallet": {"name": "Meat mallet", "cat": "prep", "url": "https://en.wikipedia.org/wiki/Tenderising_mallet",
        "blurb": "One side spikes, one side flattens. Even thickness is the whole secret of cutlets that cook at the same speed."},
    "rolling-pin": {"name": "Rolling pin", "cat": "bake", "url": "https://en.wikipedia.org/wiki/Rolling_pin",
        "blurb": "Even thickness or bust - a crust is only as honest as its thinnest spot."},
    "pie-dish": {"name": "Pie dish", "cat": "bake", "url": "https://en.wikipedia.org/wiki/Pie",
        "blurb": "Glass shows you the crust's underside; ceramic browns it harder. Either way, the crimp is yours to live with."},
    "sheet-pan": {"name": "Sheet pan", "cat": "bake", "url": "https://en.wikipedia.org/wiki/Sheet_pan",
        "blurb": "The kitchen's stage: roasting, broiling, proofing, catching drips, feeding a crowd at midnight."},
    "wire-rack": {"name": "Wire rack", "cat": "bake", "url": "https://en.wikipedia.org/wiki/Cookware_and_bakeware",
        "blurb": "Air under fried things keeps the bottom crisp. Steam is the enemy of everything you just worked for."},
    "pizza-stone": {"name": "Pizza stone / steel", "cat": "bake", "url": "https://en.wikipedia.org/wiki/Pizza_stone",
        "blurb": "Pre-heated mass that plays the floor of a bread oven. The leopard-spotted blister comes from here, not from hope."},
    "food-processor": {"name": "Food processor", "cat": "machines", "url": "https://en.wikipedia.org/wiki/Food_processor",
        "blurb": "Blades do in eight seconds what knives do in eight minutes. Falafel paste is its hometown."},
    "blender": {"name": "Blender", "cat": "machines", "url": "https://en.wikipedia.org/wiki/Blender",
        "blurb": "For sauces that must be silk, not texture. Butter chicken's quiet hero, standing behind the marinade."},
    "immersion-blender": {"name": "Immersion blender", "cat": "machines", "url": "https://en.wikipedia.org/wiki/Immersion_blender",
        "blurb": "Purees soup in the pot. One less thing to wash, one more thing to love."},
    "stand-mixer": {"name": "Stand mixer", "cat": "machines", "url": "https://en.wikipedia.org/wiki/Mixer_(cooking)",
        "blurb": "Kneads while you read. Strictly optional, but so is sleep."},
    "rice-cooker": {"name": "Rice cooker", "cat": "machines", "url": "https://en.wikipedia.org/wiki/Rice_cooker",
        "blurb": "Click, forget, perfect. The most honest appliance in the kitchen - it tells you exactly when it is done."},
}

EQUIPMENT = {
    "apple-pie": [
        {"t": "mixing-bowl"}, {"t": "kitchen-scale", "n": "butter and flour by weight - crust is math"},
        {"t": "chefs-knife"}, {"t": "citrus-juicer", "n": "the lemon keeps the apples from browning"},
        {"t": "rolling-pin"}, {"t": "pie-dish"}, {"t": "pastry-brush", "n": "egg wash for the lacquered top"},
        {"t": "oven"},
    ],
    "authentic-carbonara": [
        {"t": "stockpot"}, {"t": "frying-pan", "n": "heavy - cast iron or stainless, for rendering the guanciale"},
        {"t": "cutting-board"}, {"t": "chefs-knife"}, {"t": "mixing-bowl"}, {"t": "whisk"},
        {"t": "box-grater", "n": "pecorino, grated fine enough to melt instantly"},
        {"t": "pepper-mill", "n": "coarse crack - pre-ground pepper is a different dish"},
        {"t": "colander"},
    ],
    "baja-fish-tacos": [
        {"t": "chefs-knife"}, {"t": "cutting-board"}, {"t": "cast-iron-skillet", "n": "two fingers of oil - or any heavy pot"},
        {"t": "thermometer", "n": "oil at 180 C; guessing is how fish gets greasy"},
        {"t": "wire-rack", "n": "drain on air, never on paper towels"}, {"t": "whisk"}, {"t": "mixing-bowl"},
        {"t": "citrus-juicer"},
    ],
    "baked-mac-and-cheese": [
        {"t": "stockpot"}, {"t": "saucepan", "n": "the roux wants a tall, heavy pan"},
        {"t": "whisk", "n": "the bechamel's personal trainer"}, {"t": "box-grater"},
        {"t": "baking-dish"}, {"t": "colander"}, {"t": "oven"},
    ],
    "beef-bourguignon": [
        {"t": "dutch-oven", "n": "the entire recipe happens inside this one pot"},
        {"t": "chefs-knife"}, {"t": "cutting-board"}, {"t": "wooden-spoon"},
        {"t": "fine-sieve", "n": "strain the braising liquid - silk, not stew with lumps"},
        {"t": "ladle"}, {"t": "kitchen-twine", "n": "holds the bouquet garni together"},
        {"t": "oven"},
    ],
    "bibimbap": [
        {"t": "rice-cooker"}, {"t": "frying-pan", "n": "each vegetable cooks separately - yes, all of them, sorry"},
        {"t": "cast-iron-skillet", "n": "the dolsot's understudy, for the crackling rice bottom"},
        {"t": "chefs-knife"}, {"t": "cutting-board"}, {"t": "mixing-bowl"},
    ],
    "butter-chicken": [
        {"t": "mixing-bowl", "n": "the yogurt marinade, overnight"}, {"t": "cast-iron-skillet", "n": "char the chicken hard first - the smoke spots are flavor"},
        {"t": "blender", "n": "the sauce must be silk, not texture"}, {"t": "saucepan"}, {"t": "wooden-spoon"},
        {"t": "chefs-knife"}, {"t": "cutting-board"},
    ],
    "carnitas": [
        {"t": "dutch-oven", "n": "lard, orange, patience - the confit happens here"},
        {"t": "chefs-knife"}, {"t": "cutting-board"}, {"t": "sheet-pan", "n": "the crisping finale under the broiler"},
        {"t": "oven"}, {"t": "tongs", "n": "pull the pork apart, do not shred it politely"},
    ],
    "chana-masala": [
        {"t": "mortar-pestle", "n": "bloom the spices fresh - or toast and grind them"},
        {"t": "frying-pan"}, {"t": "wooden-spoon"}, {"t": "chefs-knife"}, {"t": "cutting-board"},
        {"t": "citrus-juicer", "n": "the finishing squeeze is not optional"},
    ],
    "chicken-katsu-curry": [
        {"t": "meat-mallet", "n": "even thickness is even crunch"}, {"t": "frying-pan", "n": "a centimeter of oil, shallow fry, no more"},
        {"t": "thermometer", "n": "170 C - panko burns above it and sulks below it"},
        {"t": "wire-rack", "n": "drain on air so the crust stays loud"}, {"t": "saucepan", "n": "the curry gravy"},
        {"t": "rice-cooker"}, {"t": "tongs"}, {"t": "chefs-knife"}, {"t": "cutting-board"},
    ],
    "chicken-noodle-soup": [
        {"t": "stockpot"}, {"t": "cutting-board"}, {"t": "chefs-knife"}, {"t": "ladle"},
        {"t": "colander"}, {"t": "wooden-spoon"},
    ],
    "chicken-shawarma": [
        {"t": "mixing-bowl", "n": "the marinade is seven layers deep"}, {"t": "oven", "n": "fake the spit: stack the meat, roast hot, then broil"},
        {"t": "sheet-pan", "n": "the stacked tower roasts right on it"},
        {"t": "cast-iron-skillet", "n": "the final crisp in its own fat"},
        {"t": "chefs-knife", "n": "shave it thin like the street vendors do"}, {"t": "cutting-board"},
    ],
    "chicken-souvlaki": [
        {"t": "mixing-bowl"}, {"t": "skewers", "n": "soak wooden ones 30 minutes or sacrifice them"},
        {"t": "grill", "n": "or a grill pan - the stripes are flavor"},
        {"t": "citrus-juicer"}, {"t": "tongs"}, {"t": "thermometer", "n": "pull at 74 C, rest, be happy"},
        {"t": "chefs-knife"}, {"t": "cutting-board"},
    ],
    "chocolate-lava-cake": [
        {"t": "ramekin", "n": "buttered and sugared like you mean it - this is the escape route"},
        {"t": "saucepan", "n": "melt the chocolate gently, or a bowl over it"},
        {"t": "mixing-bowl"}, {"t": "whisk"}, {"t": "oven", "n": "12 minutes at 200 C - the recipe is a stopwatch"},
    ],
    "classic-margherita-pizza": [
        {"t": "kitchen-scale", "n": "dough is math; cups are folklore"},
        {"t": "mixing-bowl"}, {"t": "bench-scraper", "n": "divide the dough, stretch with hands not pins"},
        {"t": "sheet-pan", "n": "for proofing the balls"},
        {"t": "pizza-stone", "n": "pre-heat a full hour - the blister lives here"},
        {"t": "oven", "n": "as hot as it legally goes, 280 C if it has it"},
    ],
    "creme-brulee": [
        {"t": "saucepan", "n": "scald the cream - it changes the proteins, really"},
        {"t": "mixing-bowl"}, {"t": "whisk"}, {"t": "fine-sieve", "n": "strain the custard. Always. No witnesses needed"},
        {"t": "ramekin"}, {"t": "baking-dish", "n": "the water bath - hot but not boiling"},
        {"t": "oven"}, {"t": "thermometer", "n": "custard sets at 80 C; above that, it weeps"},
        {"t": "blowtorch", "n": "the finale - 5 cm from the sugar, keep it moving"},
    ],
    "falafel-tahini": [
        {"t": "food-processor", "n": "soaked chickpeas, never cooked - the machine makes the paste"},
        {"t": "colander", "n": "the overnight soak exits here"}, {"t": "mixing-bowl"},
        {"t": "cast-iron-skillet", "n": "2-3 cm of neutral oil"},
        {"t": "thermometer", "n": "175 C, and drop the dough in cold"},
        {"t": "spider", "n": "lift them out before the second crunch"}, {"t": "mortar-pestle", "n": "garlic for the tahini sauce"},
        {"t": "citrus-juicer"},
    ],
    "french-onion-soup": [
        {"t": "dutch-oven", "n": "45 minutes of onions - the pot forgives everything"},
        {"t": "chefs-knife"}, {"t": "cutting-board"}, {"t": "wooden-spoon", "n": "stir the fond loose, that brown glaze is the dish"},
        {"t": "oven"}, {"t": "ladle"},
    ],
    "mushroom-risotto": [
        {"t": "frying-pan", "n": "wide and heavy - the rice wants a shallow lake"},
        {"t": "stockpot", "n": "the stock stays steaming on the next burner"},
        {"t": "ladle", "n": "one circle of stock at a time"}, {"t": "wooden-spoon", "n": "the official tool of risotto"},
        {"t": "microplane", "n": "parmesan snow, grated at the last second"},
        {"t": "chefs-knife"}, {"t": "cutting-board"},
    ],
    "no-knead-sourdough": [
        {"t": "kitchen-scale", "n": "baker's percentages - flour is math"},
        {"t": "mixing-bowl", "n": "one bowl, one day"}, {"t": "bench-scraper", "n": "folds and shaping without sticking"},
        {"t": "thermometer", "n": "dough at 24 C is the target; the kitchen is your incubator"},
        {"t": "dutch-oven", "n": "the bread oven inside your oven"}, {"t": "oven"},
        {"t": "chefs-knife", "n": "score the loaf - confident, one centimeter deep"},
    ],
    "pad-thai": [
        {"t": "wok", "n": "hotter than you think; then hotter"}, {"t": "spatula", "n": "toss, do not stir"},
        {"t": "mixing-bowl", "n": "sauce first - everything after is a sprint"},
        {"t": "colander", "n": "soak the noodles, never boil them"},
        {"t": "chefs-knife"}, {"t": "cutting-board"}, {"t": "citrus-juicer", "n": "lime at the table, not the wok"},
    ],
    "pho-bo": [
        {"t": "stockpot", "n": "the four-hour clarity marathon"}, {"t": "fine-sieve", "n": "skim, then strain - a cloudy broth is a lost argument"},
        {"t": "chefs-knife", "n": "freeze the eye round 30 minutes, slice paper-thin"},
        {"t": "cutting-board"}, {"t": "ladle"}, {"t": "spider", "n": "blanch the noodles in seconds"}, {"t": "colander"},
    ],
    "ratatouille": [
        {"t": "frying-pan", "n": "each vegetable cooks separately - the church of ratatouille"},
        {"t": "stockpot", "n": "where they finally meet the tomato"}, {"t": "wooden-spoon"},
        {"t": "chefs-knife", "n": "or a mandoline if you are doing the byaldi thing"}, {"t": "cutting-board"},
    ],
    "seafood-paella": [
        {"t": "paella-pan", "n": "wide as your burner allows - rice in one layer, thin"},
        {"t": "stove"}, {"t": "wooden-spoon", "n": "a spoon you will deliberately not use once the stock goes in"},
        {"t": "chefs-knife"}, {"t": "cutting-board"}, {"t": "citrus-juicer", "n": "lemon wedges arrive at the end"},
    ],
    "shepherds-pie": [
        {"t": "dutch-oven", "n": "the stew is born here"}, {"t": "potato-masher", "n": "roofs with texture - machines make glue"},
        {"t": "baking-dish", "n": "fork-ridged, golden, non-negotiable"},
        {"t": "chefs-knife"}, {"t": "cutting-board"}, {"t": "wooden-spoon"}, {"t": "oven"},
    ],
    "shoyu-ramen": [
        {"t": "stockpot", "n": "the broth is built in layers here"}, {"t": "fine-sieve", "n": "strain before the tare goes in"},
        {"t": "saucepan", "n": "warms the tare and the toppings"}, {"t": "ladle"},
        {"t": "colander", "n": "noodles get their own water - never the broth's"}, {"t": "tongs"}, {"t": "chefs-knife"}, {"t": "cutting-board"},
    ],
    "smash-burger": [
        {"t": "cast-iron-skillet", "n": "flat-top substitute; pre-heat until it just smokes"},
        {"t": "spatula", "n": "stiff, metal - you will smash with it"},
        {"t": "bench-scraper", "n": "the flip-and-scrape trick keeps the crust on the patty"},
        {"t": "chefs-knife", "n": "onion shaved to translucent whispers"}, {"t": "cutting-board"},
    ],
    "spaghetti-aglio-e-olio": [
        {"t": "stockpot"}, {"t": "frying-pan", "n": "cold pan, cold garlic - low heat is the entire game"},
        {"t": "chefs-knife", "n": "garlic sliced, never pressed"}, {"t": "cutting-board"},
        {"t": "tongs", "n": "toss in the pan, pasta water still dripping"}, {"t": "colander"},
    ],
    "spanish-tortilla": [
        {"t": "frying-pan", "n": "nonstick or well-seasoned, 20-22 cm - the flip needs a plate larger than the pan and one deep breath"},
        {"t": "mandoline", "n": "potatoes at 3 mm, even; or a very calm knife"},
        {"t": "mixing-bowl"}, {"t": "spatula"}, {"t": "chefs-knife"}, {"t": "cutting-board"},
    ],
    "tiramisu": [
        {"t": "mixing-bowl"}, {"t": "whisk", "n": "or a hand mixer for the yolk ribbons"},
        {"t": "saucepan", "n": "the zabaglione, over simmering water"}, {"t": "spatula", "n": "fold, do not stir"},
        {"t": "fine-sieve", "n": "the cocoa snowfall at the end"},
    ],
}

FACTS = {
    "apple-pie": {
        "course": "Dessert", "base": "plant — orchard fruit under wheat", "origin": "England, then everywhere",
        "first_recorded": "1381 — a printed recipe in The Forme of Cury", "name_means": "Exactly what it says. The honesty is the point.",
        "technique": "Blind bake the bottom, thicken the filling, vent the roof",
        "heat": 0, "budget": "$", "season": "Autumn — pie weather",
        "signature": "Cinnamon, butter pastry, apples holding their shape",
        "serve_at": "Warm, with cold cream running into the gap", "pour": "Hot coffee, or cold cider if you have it",
        "wiki": "https://en.wikipedia.org/wiki/Apple_pie",
    },
    "authentic-carbonara": {
        "course": "Main — pasta", "base": "meat — cured pork jowl", "origin": "Rome, Lazio, Italy",
        "first_recorded": "c. 1950 — startlingly young for something this canonized",
        "name_means": "Most likely from carbonaro, 'charcoal worker' — though Rome argues about it daily.",
        "technique": "Off-heat emulsion: eggs, cheese, pasta water, nerve",
        "heat": 1, "budget": "$$", "season": "Any — carbonara ignores the calendar",
        "signature": "Guanciale fat, sheep's-milk salt, black pepper warmth",
        "serve_at": "Immediately — the sauce peaks for about 90 seconds", "pour": "Frascati, or any Roman white you would drink chilled",
        "wiki": "https://en.wikipedia.org/wiki/Carbonara",
    },
    "baja-fish-tacos": {
        "course": "Street food", "base": "seafood — white fish, fried", "origin": "Baja California, Mexico",
        "first_recorded": "Mid-1900s Ensenada and Rosarito; Japanese immigrants brought the tempura crunch",
        "name_means": "Named for the peninsula, not the fish — the fish is whatever came in that morning.",
        "technique": "Tempura-style fry + cold crema against hot fish",
        "heat": 2, "budget": "$", "season": "Summer, ideally within earshot of the Pacific",
        "signature": "Crackling batter, lime, chipotle crema, cold cabbage",
        "serve_at": "Standing up, within sixty seconds of frying", "pour": "Lager with lime, or a very cold Pacifico",
        "wiki": "https://en.wikipedia.org/wiki/Tacos_de_pescado",
    },
    "baked-mac-and-cheese": {
        "course": "Main — or the side that eats like a main", "base": "dairy — a cheese sauce with pasta in it", "origin": "Britain, adopted and roofed by America",
        "first_recorded": "1390s — 'makerouns' in The Forme of Cury; Thomas Jefferson later shipped a macaroni machine home",
        "name_means": "Macaroni comes from Italian maccaruni — and nobody is sure where that came from either.",
        "technique": "Roux → béchamel → mornay, then a golden gratin lid",
        "heat": 0, "budget": "$", "season": "Winter, custody battles and potlucks",
        "signature": "Sharp cheddar depth, nutmeg whisper, crusty top",
        "serve_at": "Bubbling, five minutes out of the oven — no sooner", "pour": "Crisp pilsner or an unoaked Chardonnay",
        "wiki": "https://en.wikipedia.org/wiki/Macaroni_and_cheese",
    },
    "beef-bourguignon": {
        "course": "Main — braise", "base": "meat — beef chuck, wine-braised", "origin": "Burgundy, France",
        "first_recorded": "A peasant braise for centuries; codified in print in the 19th century, canonized by Escoffier",
        "name_means": "Burgundy-style beef — named for the wine it was born next to.",
        "technique": "Wine braise, staged reductions, pearl onions on the side",
        "heat": 0, "budget": "$$$", "season": "Deep winter — snow outside is ideal",
        "signature": "Red-wine depth, thyme, glossy sauce that coats a spoon",
        "serve_at": "The day after you made it, honestly", "pour": "The same Burgundy you cooked with — it earned it",
        "wiki": "https://en.wikipedia.org/wiki/Beef_bourguignon",
    },
    "bibimbap": {
        "course": "Main — rice bowl", "base": "mixed — vegetables, beef, egg", "origin": "Jeonju, South Korea",
        "first_recorded": "Late 1800s — first written down in the cookbook Siuijeonseo",
        "name_means": "Literally 'mixed rice' (bibim = mixed, bap = rice). The recipe is the instruction manual for itself.",
        "technique": "Every component cooked separately, mixed only at the table",
        "heat": 2, "budget": "$$", "season": "Any — gochujang is all-weather",
        "signature": "Toasted sesame, gochujang warmth, crackling stone-bowl rice",
        "serve_at": "Hot, with a raw egg yolk you stir in yourself", "pour": "Makgeolli, or barley tea if it is lunch",
        "wiki": "https://en.wikipedia.org/wiki/Bibimbap",
    },
    "butter-chicken": {
        "course": "Main — curry", "base": "meat — chicken, tandoor-adjacent", "origin": "Delhi, India",
        "first_recorded": "1950s — Moti Mahal restaurant, tandoori chicken rescued by tomato-butter gravy",
        "name_means": "Murgh makhani — 'butter chicken', named with characteristic directness.",
        "technique": "Marinade → hard char → silk sauce → a finish of cream and butter",
        "heat": 2, "budget": "$$", "season": "Any — this is monsoon and blizzard food alike",
        "signature": "Tandoori char, tomato-tikka sweetness, fenugreek finish",
        "serve_at": "With naan positioned like a shovel", "pour": "Off-dry Riesling — the classic argument-winner",
        "wiki": "https://en.wikipedia.org/wiki/Butter_chicken",
    },
    "carnitas": {
        "course": "Main / street food", "base": "meat — pork shoulder", "origin": "Michoacán, Mexico",
        "first_recorded": "Colonial era — copper pots, rendered lard, whole villages' Sunday plans",
        "name_means": "'Little meats' — the pork is confited in big pieces then broken small.",
        "technique": "Lard confit, then a hard crisp under the broiler",
        "heat": 1, "budget": "$", "season": "Any — taco night has no season",
        "signature": "Deep pork richness, orange brightness, edges like candy",
        "serve_at": "In warm tortillas with salsa, immediately", "pour": "Michelada, or horchata for the afternoon shift",
        "wiki": "https://en.wikipedia.org/wiki/Carnitas",
    },
    "chana-masala": {
        "course": "Main — curry", "base": "plant — chickpeas entirely", "origin": "Punjab, North India",
        "first_recorded": "No single birthday — chickpeas have been in the subcontinent for millennia, the spice layering is Mughal-era craft",
        "name_means": "Chana = chickpeas, masala = the spice mix. Case closed, lunch served.",
        "technique": "Blooming spices in oil before anything wet is allowed in",
        "heat": 2, "budget": "$", "season": "Any — the cheapest great dinner there is",
        "signature": "Toasted cumin, amchoor sourness, ginger heat",
        "serve_at": "With rice or bhature — mop, do not sip", "pour": "Mango lassi, cold enough to argue back",
        "wiki": "https://en.wikipedia.org/wiki/Chana_masala",
    },
    "chicken-katsu-curry": {
        "course": "Main — rice + curry + cutlet", "base": "meat — breaded chicken", "origin": "Japan, via the Royal Navy via Anglo-Indian curry",
        "first_recorded": "1870s–90s Meiji era; the breaded cutlet itself dates to 1899 at Rengatei, Ginza",
        "name_means": "Katsu is a squeeze of katsuretsu, Japan's take on 'cutlet'.",
        "technique": "Panko crust fried loud, curry gravy ladled to the edge",
        "heat": 1, "budget": "$", "season": "Any — exam-season comfort in Japan",
        "signature": "Panko shatter, sweet-dark curry silk, pickles to cut it",
        "serve_at": "With the cutlet sliced, still audible", "pour": "An ice-cold lager, seriously",
        "wiki": "https://en.wikipedia.org/wiki/Chicken_katsu",
    },
    "chicken-noodle-soup": {
        "course": "Soup", "base": "meat — chicken, whole poached", "origin": "Everywhere, via the Jewish shtetl to America",
        "first_recorded": "Chicken soup as medicine: Maimonides recommended it in the 12th century",
        "name_means": "Three nouns, one truth. The Jewish penicillin joke is only half a joke.",
        "technique": "Gentle poach, skim twice, noodles in last",
        "heat": 1, "budget": "$", "season": "Winter, and any fever",
        "signature": "Golden fat beads, dill, celery backbone",
        "serve_at": "Scalding, with the best bread in the house", "pour": "Smoky black tea, or nothing at all",
        "wiki": "https://en.wikipedia.org/wiki/Chicken_soup",
    },
    "chicken-shawarma": {
        "course": "Street food", "base": "meat — chicken, spit-roasted", "origin": "The Ottoman Levant — Bursa to Damascus to Beirut",
        "first_recorded": "1870s — the rotating vertical spit (döner) is invented in Bursa",
        "name_means": "From Turkish çevirme, 'turning'. The Arabic word took the trip and stayed.",
        "technique": "Layered yogurt-spice marinade, stacked roast, razor shavings",
        "heat": 2, "budget": "$", "season": "Any — it is a street, streets do not close",
        "signature": "Turmeric-turmeric-turmeric, garlic toum, charred edges",
        "serve_at": "Wrapped tight, eaten leaning over paper", "pour": "Ayran — the salted yogurt drink that cools everything down",
        "wiki": "https://en.wikipedia.org/wiki/Shawarma",
    },
    "chicken-souvlaki": {
        "course": "Street food", "base": "meat — chicken chunks, skewered", "origin": "Greece",
        "first_recorded": "3,600 years — stone cooking lines for skewers found at Akrotiri, Santorini",
        "name_means": "Diminutive of souvla (big skewer) — 'little skewer', said with affection.",
        "technique": "Lemon-oregano marinade, high fire, rest, wrap",
        "heat": 1, "budget": "$", "season": "Summer — ideally with sand nearby",
        "signature": "Charred lemon, oregano, garlic yogurt",
        "serve_at": "Off the skewer, in pita, at golden hour", "pour": "Retsina — pine resin wine, an acquired taste worth acquiring",
        "wiki": "https://en.wikipedia.org/wiki/Souvlaki",
    },
    "chocolate-lava-cake": {
        "course": "Dessert", "base": "dairy — chocolate, butter, eggs", "origin": "France (Michel Bras) and New York — parallel claims",
        "first_recorded": "1981–87 — Bras' frozen-ganache coulant; NYC chefs claim the same idea independently",
        "name_means": "Bras called his a coulant — 'flowing'. Americans went with what they saw.",
        "technique": "Underbake on purpose: set walls, liquid center",
        "heat": 0, "budget": "$$", "season": "Any — restaurant desserts ignore seasons",
        "signature": "Bittersweet molten center, barely-set crumb",
        "serve_at": "Within four minutes, or not at all", "pour": "Cold milk, or an espresso if you are pretending it is late",
        "wiki": "https://en.wikipedia.org/wiki/Chocolate_lava_cake",
    },
    "classic-margherita-pizza": {
        "course": "Main — pizza", "base": "plant — tomato and basil over dairy", "origin": "Naples, Italy",
        "first_recorded": "1889 — the Queen Margherita legend at Pizzeria Brandi; tomato-cheese pizzas are older than the story",
        "name_means": "Named for a queen, colored like a flag: tomato, mozzarella, basil.",
        "technique": "Fermented dough, hand-stretched, blistering floor heat",
        "heat": 0, "budget": "$", "season": "Any — but August tomatoes cheat",
        "signature": "Charred leopard crust, sweet tomato, milky fior di latte",
        "serve_at": "Cut on the board, folded, devoured — three minutes of prime", "pour": "Chilled Lambrusco, no apologies",
        "wiki": "https://en.wikipedia.org/wiki/Pizza_margherita",
    },
    "creme-brulee": {
        "course": "Dessert", "base": "dairy — cream, egg yolks, sugar", "origin": "France, England and Catalonia — all three claim it",
        "first_recorded": "1691 — Massialot's cookbook; Trinity College's 'burnt cream' and crema catalana say otherwise",
        "name_means": "'Burnt cream' — the one recipe where scorching is the finish line.",
        "technique": "Water-bath custard, chilled overnight, torched to glass",
        "heat": 0, "budget": "$$", "season": "Any — it is a candle-lit constant",
        "signature": "Vanilla custard under shattering caramel glass",
        "serve_at": "Cold center, hot lid — the 30-second window after the torch", "pour": "Sauternes, the textbook answer that is also the right one",
        "wiki": "https://en.wikipedia.org/wiki/Cr%C3%A8me_br%C3%BBl%C3%A9e",
    },
}

FACTS.update({
    "falafel-tahini": {
        "course": "Street food", "base": "plant — chickpeas and herbs, fried", "origin": "Egypt; the Levant claims it too and neither will blink first",
        "first_recorded": "1882 in an Egyptian cookbook; the oral history is older than print",
        "name_means": "From Arabic falāfil — possibly a plural of filfil, 'pepper'. Small word, big argument.",
        "technique": "Soaked (never cooked) chickpeas ground raw — the law of the dish",
        "heat": 1, "budget": "$", "season": "Any — but Middle Eastern summer is its home turf",
        "signature": "Herb-green interior, sesame crunch, garlic tahini",
        "serve_at": "In pita with pickles, still cooling from the oil", "pour": "Mint lemonade, heavily iced",
        "wiki": "https://en.wikipedia.org/wiki/Falafel",
    },
    "french-onion-soup": {
        "course": "Soup", "base": "plant — onions, hours of them", "origin": "Paris — Les Halles, the old belly of the city",
        "first_recorded": "1651 — La Varenne prints an onion soup; Les Halles market workers made it a religion",
        "name_means": "Soupe à l'oignon. It never needed a fancier name.",
        "technique": "Deep caramelization (45+ min), deglaze, gratinéed lid",
        "heat": 0, "budget": "$", "season": "Late autumn through the last frost",
        "signature": "Dark amber sweetness, beef depth, molten gruyère lid",
        "serve_at": "Under the cheese lid, with a spoon that reaches the bottom", "pour": "Côtes du Rhône, rustic and unbothered",
        "wiki": "https://en.wikipedia.org/wiki/French_onion_soup",
    },
    "mushroom-risotto": {
        "course": "Main — risotto", "base": "plant — mushrooms over rice and butter", "origin": "Northern Italy — Milan and the Po valley",
        "first_recorded": "1574 — the saffron-stained Duomo glassworker legend in Milan; codified by the 19th century",
        "name_means": "Risotto from riso, rice — the dish named after the grain it worships.",
        "technique": "Starch cultivation: toast, ladle, stir, never rush",
        "heat": 0, "budget": "$$", "season": "Autumn — porcini season, obviously",
        "signature": "Roasted mushroom depth, parmesan, all'onda wave",
        "serve_at": "All'onda — it should ripple when you shake the plate", "pour": "Gavi, or Barbera if the mushrooms were wild",
        "wiki": "https://en.wikipedia.org/wiki/Risotto",
    },
    "no-knead-sourdough": {
        "course": "Bread", "base": "grain — flour, water, salt, time", "origin": "Ancient Egypt by lineage; this exact recipe is 2006 New York",
        "first_recorded": "Bread itself: ~3000 BC Egypt. The no-knead method: Jim Lahey, 2006, front page of the New York Times dining section",
        "name_means": "The name is the recipe: no kneading. The dough does the work while you sleep.",
        "technique": "Wild-yeast fermentation, long autolyse, Dutch-oven steam",
        "heat": 0, "budget": "$", "season": "Any — the starter never rests",
        "signature": "Crackled crust, lactic sourness, open crumb",
        "serve_at": "Cooled at least an hour — cutting early is a crime scene", "pour": "Salted butter, standing by",
        "wiki": "https://en.wikipedia.org/wiki/Sourdough",
    },
    "pad-thai": {
        "course": "Main — noodles", "base": "mixed — shrimp, egg, peanut over rice noodles", "origin": "Thailand — a Bangkok government campaign that outlived the government",
        "first_recorded": "1930s–40s — promoted nationally under PM Plaek Phibunsongkhram to build a Thai noodle identity",
        "name_means": "Simply 'Thai-style stir-fry' — a nationalism project you can order in three minutes.",
        "technique": "Sauce-first wok sprint: soak, toss, finish in seconds",
        "heat": 1, "budget": "$", "season": "Any — Bangkok does not do seasons",
        "signature": "Tamarind sour-sweet, fish sauce depth, peanut crunch",
        "serve_at": "Chopped peanuts and lime at the table, mixed by the eater", "pour": "Thai iced tea, or a Singha if the evening allows",
        "wiki": "https://en.wikipedia.org/wiki/Pad_thai",
    },
    "pho-bo": {
        "course": "Soup — noodle", "base": "meat — beef, clear-brothed", "origin": "Hanoi, Vietnam",
        "first_recorded": "c. 1900–1910 — street stalls in Hanoi, with French colonial beef demand in the background",
        "name_means": "Pronounced 'fuh?' — theories run from French feu (pot-au-feu) to the cry of vendors. Nobody knows. Slurp anyway.",
        "technique": "Clarity above all: parboil, skim, char the aromatics",
        "heat": 2, "budget": "$$", "season": "Any — breakfast in Hanoi is 5 AM",
        "signature": "Star anise, charred ginger, Thai basil on top",
        "serve_at": "With the plate of herbs to build as you go", "pour": "Jasmine tea, or a bia hoi if it is that hour",
        "wiki": "https://en.wikipedia.org/wiki/Pho",
    },
    "ratatouille": {
        "course": "Main — vegetable stew", "base": "plant — zucchini, eggplant, pepper, tomato", "origin": "Nice, France",
        "first_recorded": "18th century — the word ratatolha is older than any written recipe",
        "name_means": "From Occitan ratatolha — related to touiller, 'to stir things up'.",
        "technique": "Cook each vegetable separately, then marry them low and slow",
        "heat": 0, "budget": "$", "season": "Summer — when the vegetables need no help",
        "signature": "Olive oil gloss, basil, sweetness coaxed from nothing",
        "serve_at": "Warm or room temperature — better the second day", "pour": "Bandol rosé, cold",
        "wiki": "https://en.wikipedia.org/wiki/Ratatouille",
    },
    "seafood-paella": {
        "course": "Main — rice", "base": "seafood — shrimp, mussels, squid", "origin": "Valencia, Spain — the coastal cousin of the original",
        "first_recorded": "19th century — rice paddies of the Albufera, cooked over orange-wood fires",
        "name_means": "Paella is the Valencian word for the pan itself — from Latin patella. The dish is named after its stage.",
        "technique": "Socarrat engineering: one layer, no stirring, listen for crackle",
        "heat": 1, "budget": "$$$", "season": "Summer — outdoors, ideally with arguments about it",
        "signature": "Saffron gold, smoked paprika, the crackled rice floor",
        "serve_at": "Straight from the pan, everyone at their own wedge", "pour": "Albariño, or Cava if there is something to celebrate",
        "wiki": "https://en.wikipedia.org/wiki/Paella",
    },
    "shepherds-pie": {
        "course": "Main — baked pie", "base": "meat — ground lamb under potato", "origin": "Britain and Ireland — farmhouse leftovers turned institution",
        "first_recorded": "1791 — 'cottage pie' in print; the shepherd's name for the lamb version stuck later",
        "name_means": "Shepherd's because it is lamb; cottage because it is beef. The internet forgets this weekly.",
        "technique": "Stew below, mash roof above, fork ridges for the golden crust",
        "heat": 1, "budget": "$", "season": "Winter — it is a blanket you can eat",
        "signature": "Worcestershire depth, rosemary, potato roof with brown peaks",
        "serve_at": "Resting ten minutes or it runs — patience, briefly", "pour": "A bitter ale, room-temperature British",
        "wiki": "https://en.wikipedia.org/wiki/Shepherd%27s_pie",
    },
    "shoyu-ramen": {
        "course": "Soup — noodle", "base": "mixed — chicken broth, pork chashu, egg", "origin": "Japan, via Chinese noodle shops",
        "first_recorded": "1910 — Rairaiken opens in Tokyo and the Japanese ramen era begins",
        "name_means": "Shoyu = soy sauce — the tare, the seasoning layer that names the whole bowl.",
        "technique": "Layered broth + tare + noodles cooked separately, always",
        "heat": 1, "budget": "$$", "season": "Any — but a cold night makes it spiritual",
        "signature": "Clear amber broth, chashu fat, ajitama yolk",
        "serve_at": "Scalding. Slurp — it is aeration, not rudeness", "pour": "Cold lager, or nothing before the broth is gone",
        "wiki": "https://en.wikipedia.org/wiki/Ramen",
    },
    "smash-burger": {
        "course": "Street food", "base": "meat — beef, smashed thin", "origin": "American diners and drive-ins",
        "first_recorded": "2000s — the crust became the point; the Smashburger brand arrived 2007 and the style went national",
        "name_means": "Named after the verb. The whole technique is in the smash.",
        "technique": "Maillard maximization: smash thin, scrape, flip once",
        "heat": 0, "budget": "$", "season": "Any — it is diner food, diners have no season",
        "signature": "Lacy beef crust, melted American, steam-softened onions",
        "serve_at": "In the paper wrapper, slightly crushed on purpose", "pour": "A vanilla milkshake — the correct answer",
        "wiki": "https://en.wikipedia.org/wiki/Hamburger",
    },
    "spaghetti-aglio-e-olio": {
        "course": "Main — pasta", "base": "grain — pasta with garlic and olive oil", "origin": "Naples, Italy — la cucina povera",
        "first_recorded": "Cooked for centuries before it was written down; printed recipes only settle in the 19th–20th century",
        "name_means": "Literally 'garlic and oil'. The recipe is the menu.",
        "technique": "Infusing oil, never burning garlic, emulsion nerve",
        "heat": 1, "budget": "$", "season": "Midnight, year-round",
        "signature": "Golden garlic, peperoncino bite, olive oil silk",
        "serve_at": "Twice out of the pan — it waits for no one either", "pour": "Chianti, or the last of whatever is open",
        "wiki": "https://en.wikipedia.org/wiki/Aglio_e_olio",
    },
    "spanish-tortilla": {
        "course": "Main — or tapa, or breakfast", "base": "egg — with potato and onion", "origin": "Spain — Basque Country and Navarra both claim it",
        "first_recorded": "First written mention 1817; the Carlist-general legends are later decorations",
        "name_means": "Tortilla here means 'little cake' — nothing to do with the Mexican kind, a fact learned by everyone once, awkwardly.",
        "technique": "Low-slow potato confit, then the flip (one plate, one breath)",
        "heat": 0, "budget": "$", "season": "Any — it is lunch, dinner and midnight alike",
        "signature": "Silky potato interior, jammy center, olive oil richness",
        "serve_at": "Room temperature — which is its superpower", "pour": "Albariño, or nothing — tortilla travels alone",
        "wiki": "https://en.wikipedia.org/wiki/Spanish_omelette",
    },
    "tiramisu": {
        "course": "Dessert", "base": "dairy — mascarpone, eggs, coffee-soaked savoiardi", "origin": "Treviso, Italy",
        "first_recorded": "1969–72 — Le Beccherie restaurant; the Cannella/Carminati claims came later",
        "name_means": "'Pick me up' (tirami sù) — the most literal dessert name in Italy.",
        "technique": "Zabaglione + fold + overnight rest — build, chill, wait",
        "heat": 0, "budget": "$$", "season": "Any — better tomorrow anyway",
        "signature": "Espresso-soaked layers, cocoa dust, cloud-light mascarpone",
        "serve_at": "Cold, sliced with a clean knife, next day ideally", "pour": "A double espresso, obviously — commit to the theme",
        "wiki": "https://en.wikipedia.org/wiki/Tiramisu",
    },
})

TOOL_CATS = {
    "blades": "Blades & boards",
    "pots": "Pots & pans",
    "fire": "Fire & heat",
    "prep": "Prep & measure",
    "bake": "Baking & pastry",
    "machines": "Machines",
}

CLUSTERS = {
    "noodle-soups": {
        "note": "Three answers to one question. Tokyo says soy and wheat; Hanoi says clarity and rice; your grandmother says chicken.",
        "members": ["chicken-noodle-soup", "pho-bo", "shoyu-ramen"],
    },
    "marinated-chicken": {
        "note": "Same idea, two empires: the rotating shaved roast (Ottoman) versus the lemon-oregano skewer (Greek).",
        "members": ["chicken-shawarma", "chicken-souvlaki"],
    },
    "gravies": {
        "note": "The gravy drawer: three kitchens that independently decided rice is a vehicle for sauce.",
        "members": ["butter-chicken", "chana-masala", "chicken-katsu-curry"],
    },
    "taco-school": {
        "note": "Two taco philosophies from one country: slow lard-confited pork versus tempura-crunch fish.",
        "members": ["baja-fish-tacos", "carnitas"],
    },
    "roman-pasta": {
        "note": "Roman pasta logic: no sauce, just emulsion. Fat, starch, water, nerve.",
        "members": ["authentic-carbonara", "spaghetti-aglio-e-olio"],
    },
    "rice-cookery": {
        "note": "Two rice schools that share a border: the north stirs starch in; Valencia leaves it alone until it crackles.",
        "members": ["mushroom-risotto", "seafood-paella"],
    },
    "dessert-finale": {
        "note": "The restaurant-dessert finale, three ways: underbake on purpose, torch at the table, or assemble a day early and act casual.",
        "members": ["chocolate-lava-cake", "creme-brulee", "tiramisu"],
    },
    "braised-roofed": {
        "note": "Slow braised meat, two roofs: crusty bread beside the bowl or a fork-ridged potato lid on top.",
        "members": ["beef-bourguignon", "shepherds-pie"],
    },
    "rice-bowls": {
        "note": "Bowls over rice where everything is cooked separately, then mixed at the table — by you, with intent.",
        "members": ["bibimbap", "chicken-katsu-curry"],
    },
}

USES = [
    {"recipe": "french-onion-soup", "uses": "no-knead-sourdough",
     "note": "thick slices under the gruyère — the soup's crouton, engineered"},
    {"recipe": "chicken-noodle-soup", "uses": "no-knead-sourdough",
     "note": "the official dunker — technically a side, spiritually required"},
]

SIMILAR_PAIRS = [
    {"a": "authentic-carbonara", "b": "baked-mac-and-cheese", "note": "cheese-and-starch comfort, two nations, two temperatures"},
    {"a": "pad-thai", "b": "spaghetti-aglio-e-olio", "note": "hot fat, garlic, noodles — Naples and Bangkok agree"},
    {"a": "falafel-tahini", "b": "chicken-shawarma", "note": "the street-wrap family: one plants, one shaves"},
    {"a": "falafel-tahini", "b": "chana-masala", "note": "chickpeas, promoted to main character"},
    {"a": "shoyu-ramen", "b": "french-onion-soup", "note": "deep brown broths, opposite roads: charred layers vs slow caramel"},
    {"a": "mushroom-risotto", "b": "french-onion-soup", "note": "the stirring school: meditation with a spoon"},
    {"a": "smash-burger", "b": "carnitas", "note": "crust is the point — both fried in their own fat"},
    {"a": "smash-burger", "b": "chicken-katsu-curry", "note": "the crunch is structural"},
    {"a": "spanish-tortilla", "b": "ratatouille", "note": "Mediterranean patience, best at room temperature"},
    {"a": "seafood-paella", "b": "spanish-tortilla", "note": "Spanish pan logic: shallow, confident, shared from the vessel"},
    {"a": "ratatouille", "b": "chana-masala", "note": "vegetables as the entire point"},
    {"a": "baked-mac-and-cheese", "b": "french-onion-soup", "note": "the cheese-lid club: golden tops with structural ambition"},
    {"a": "baked-mac-and-cheese", "b": "shepherds-pie", "note": "golden-topped bakes, spoon-tender insides"},
    {"a": "apple-pie", "b": "no-knead-sourdough", "note": "dough confidence: flour, patience, and a hot oven"},
    {"a": "classic-margherita-pizza", "b": "no-knead-sourdough", "note": "the fermentation culture club"},
    {"a": "butter-chicken", "b": "chicken-shawarma", "note": "yogurt-and-spice marinade logic, two empires"},
    {"a": "bibimbap", "b": "pad-thai", "note": "mixed-at-the-table energy"},
    {"a": "beef-bourguignon", "b": "carnitas", "note": "slow fat, two continents: wine braise vs lard confit"},
    {"a": "chicken-noodle-soup", "b": "french-onion-soup", "note": "restorative broths — one chicken, one onion"},
    {"a": "tiramisu", "b": "apple-pie", "note": "make-ahead desserts that taste better tomorrow"},
    {"a": "baja-fish-tacos", "b": "smash-burger", "note": "hand food, napkin abandoned"},
    {"a": "chicken-souvlaki", "b": "falafel-tahini", "note": "eastern-Mediterranean street food: skewers vs croquettes"},
]
